import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
/// This file is generated by FlutterFire CLI.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPuyJBdxF2h-dwLCadbLHrGSYTVbyniVg',
    appId: '1:126415016557:android:3b755abfd7dd8e1e3a6564',
    messagingSenderId: '126415016557',
    projectId: 'aquafeed-f3451',
    databaseURL: 'https://aquafeed-f3451-default-rtdb.firebaseio.com',
    storageBucket: 'aquafeed-f3451.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPuyJBdxF2h-dwLCadbLHrGSYTVbyniVg',
    appId: '1:126415016557:ios:3b755abfd7dd8e1e3a6564',
    messagingSenderId: '126415016557',
    projectId: 'aquafeed-f3451',
    databaseURL: 'https://aquafeed-f3451-default-rtdb.firebaseio.com',
    storageBucket: 'aquafeed-f3451.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPuyJBdxF2h-dwLCadbLHrGSYTVbyniVg',
    appId: '1:126415016557:web:3b755abfd7dd8e1e3a6564',
    messagingSenderId: '126415016557',
    projectId: 'aquafeed-f3451',
    databaseURL: 'https://aquafeed-f3451-default-rtdb.firebaseio.com',
    storageBucket: 'aquafeed-f3451.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPuyJBdxF2h-dwLCadbLHrGSYTVbyniVg',
    appId: '1:126415016557:macos:3b755abfd7dd8e1e3a6564',
    messagingSenderId: '126415016557',
    projectId: 'aquafeed-f3451',
    databaseURL: 'https://aquafeed-f3451-default-rtdb.firebaseio.com',
    storageBucket: 'aquafeed-f3451.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPuyJBdxF2h-dwLCadbLHrGSYTVbyniVg',
    appId: '1:126415016557:web:3b755abfd7dd8e1e3a6564',
    messagingSenderId: '126415016557',
    projectId: 'aquafeed-f3451',
    databaseURL: 'https://aquafeed-f3451-default-rtdb.firebaseio.com',
    storageBucket: 'aquafeed-f3451.firebasestorage.app',
  );
}